/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import DAO.MauXeDAO;
import DAO.NhaCungCapDAO;
import DAO.NhanVienDAO;
import DAO.PhieuNhapChiTietDAO;
import DAO.PhieuNhapDAO;
import DAO.XeDAO;
import entity.MauXe;
import entity.NhaCungCap;
import entity.NhanVien;
import entity.PhieuNhap;
import entity.PhieuNhapChiTiet;
import entity.Xe;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import utils.DateHelper;
import utils.DialogHelper;
import utils.ImageHelper;

/**
 *
 * @author Administrator
 */
public class PhieuNhapJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PhieuNhapJFrame
     */
    public PhieuNhapJFrame() {
        initComponents();
        init();
    }
    
    MauXeDAO mauxeDAO = new MauXeDAO();
    XeDAO xeDAO = new XeDAO();
    NhanVienDAO nvDAO = new NhanVienDAO();
    NhaCungCapDAO nccDAO = new NhaCungCapDAO();
    PhieuNhapDAO pnDAO = new PhieuNhapDAO();
    PhieuNhapChiTietDAO pnctDAO = new PhieuNhapChiTietDAO();
    int index = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lblstatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuNhap = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtTongTienPN = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblTenNvPN = new javax.swing.JLabel();
        lblTenXePN = new javax.swing.JLabel();
        cboMaNvPN = new javax.swing.JComboBox<>();
        cboNhaccPN = new javax.swing.JComboBox<>();
        txtThanhTienPN = new javax.swing.JTextField();
        cboMaXePN = new javax.swing.JComboBox<>();
        lblDonGiaPN = new javax.swing.JLabel();
        lblMauXePN = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtMaPN = new javax.swing.JTextField();
        jpnNgayNhapPN = new com.toedter.calendar.JDateChooser();
        jpnSoLuongPN = new com.toedter.components.JSpinField();
        jPanel7 = new javax.swing.JPanel();
        btnInsertPN = new javax.swing.JButton();
        btnUpdatePN = new javax.swing.JButton();
        btnDeletePN = new javax.swing.JButton();
        btnNewPN = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtTimKiemPN = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuDangNhap = new javax.swing.JMenuItem();
        mnuDangXuat = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuThoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(195, 199, 198));

        jPanel2.setBackground(new java.awt.Color(195, 199, 198));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jButton1.setText("Sản phẩm");
        jPanel2.add(jButton1);

        jButton2.setText("Hóa đơn");
        jPanel2.add(jButton2);

        jButton3.setText("Nhập hàng");
        jPanel2.add(jButton3);

        jButton4.setText("Thống kê");
        jPanel2.add(jButton4);

        jButton8.setText("Admin");
        jPanel2.add(jButton8);

        jButton5.setText("Đổi mật khẩu");
        jPanel2.add(jButton5);

        jButton6.setText("Đăng xuất");
        jPanel2.add(jButton6);

        jButton7.setText("Thoát");
        jPanel2.add(jButton7);

        lblstatus.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(26, 167, 238));
        lblstatus.setText("jLabel1");

        tblPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu nhập", "Mã xe", "Tên xe", "Màu xe", "Số lượng", "Nhà cung cấp", "Đơn giá", "Thành tiền"
            }
        ));
        tblPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhieuNhap);

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton13.setText("Thêm nhà cung cấp");
        jPanel3.add(jButton13);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Tổng tiền");
        jPanel5.add(jLabel15);

        txtTongTienPN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTongTienPN.setText("0");
        jPanel5.add(txtTongTienPN);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tên xe");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Màu xe");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Số lượng");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Đơn giá");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Thành tiền");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Mã xe");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Tên nhân viên");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Nhà cung cấp");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Ngày nhập");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Thông tin phiếu nhập");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Mã nhân viên");

        lblTenNvPN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTenNvPN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenNvPN.setText("jLabel1");

        lblTenXePN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTenXePN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenXePN.setText("jLabel3");

        cboMaNvPN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMaNvPN.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMaNvPNItemStateChanged(evt);
            }
        });

        cboNhaccPN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtThanhTienPN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtThanhTienPN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cboMaXePN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMaXePN.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMaXePNItemStateChanged(evt);
            }
        });

        lblDonGiaPN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDonGiaPN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonGiaPN.setEnabled(false);

        lblMauXePN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMauXePN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMauXePN.setText("jLabel1");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Mã phiếu nhập");

        txtMaPN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMaPN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jpnNgayNhapPN.setForeground(new java.awt.Color(59, 82, 134));
        jpnNgayNhapPN.setDateFormatString("MMMMM dd, yyyy");
        jpnNgayNhapPN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jpnSoLuongPN.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jpnSoLuongPNPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboMaNvPN, 0, 127, Short.MAX_VALUE)
                                    .addComponent(cboMaXePN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jpnSoLuongPN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTenNvPN, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(lblTenXePN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDonGiaPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboNhaccPN, 0, 152, Short.MAX_VALUE)
                                    .addComponent(lblMauXePN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtThanhTienPN)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jpnNgayNhapPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jpnNgayNhapPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenNvPN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboMaNvPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboNhaccPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblTenXePN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(cboMaXePN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMauXePN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtThanhTienPN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(lblDonGiaPN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jpnSoLuongPN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btnInsertPN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnInsertPN.setText("Thêm phiếu nhập");
        btnInsertPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertPNActionPerformed(evt);
            }
        });

        btnUpdatePN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnUpdatePN.setText("Lưu phiếu nhập");
        btnUpdatePN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePNActionPerformed(evt);
            }
        });

        btnDeletePN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDeletePN.setText("Xóa phiếu nhập");
        btnDeletePN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePNActionPerformed(evt);
            }
        });

        btnNewPN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnNewPN.setText("Tạo mới phiếu nhập");
        btnNewPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeletePN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdatePN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsertPN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInsertPN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdatePN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeletePN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNewPN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Tìm kiếm PN");
        jPanel8.add(jLabel16);

        txtTimKiemPN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTimKiemPN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKiemPNKeyPressed(evt);
            }
        });
        jPanel8.add(txtTimKiemPN);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblstatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("Hệ thống");

        mnuDangNhap.setText("Đăng nhập");
        jMenu1.add(mnuDangNhap);

        mnuDangXuat.setText("Đăng xuất");
        jMenu1.add(mnuDangXuat);
        jMenu1.add(jSeparator2);

        mnuDoiMatKhau.setText("Đổi mật khẩu");
        jMenu1.add(mnuDoiMatKhau);
        jMenu1.add(jSeparator1);

        mnuThoat.setText("Thoát");
        jMenu1.add(mnuThoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        jMenuItem1.setText("Sản phẩm");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Nhân viên");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Khách hàng");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Nhà cung cấp");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Thống kê");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Trợ giúp");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboMaNvPNItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMaNvPNItemStateChanged
        
        selectMaNV();
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMaNvPNItemStateChanged

    private void cboMaXePNItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMaXePNItemStateChanged
        
        selectMaXe();
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMaXePNItemStateChanged

    private void btnInsertPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertPNActionPerformed
        
        try {
            insertPN();
            DialogHelper.alert(this, "Nhập thành công");
        } catch (Exception e) {
            DialogHelper.alert(this, "Nhập không thành công");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertPNActionPerformed

    private void tblPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuNhapMouseClicked
        if (evt.getClickCount() == 1) {
            deletePN();
            deletePNCT();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tblPhieuNhapMouseClicked

    private void btnDeletePNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePNActionPerformed
        if (DialogHelper.confirm(this, "Bạn chắc chắn muốn xóa phiếu nhập?")) {
            try {
            deletePNCT();
            deletePN();
            DialogHelper.alert(this, "Xóa thành công");
            clear();
            clearTablePN();
            
        } catch (Exception e) {
        }
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletePNActionPerformed

    private void btnNewPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPNActionPerformed
        try {
            clear();
            clearTablePN();
        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewPNActionPerformed

    private void txtTimKiemPNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemPNKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtTongTienPN.setText("0");
            timKiemTheoMaHD();
            fillCboMaNV();
            fillNhacc();
            fillCboMaXe();
            initMaPN();
   }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemPNKeyPressed

    private void btnUpdatePNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePNActionPerformed
        try {
            luuPN();
            luuPNCT();
            DialogHelper.alert(this, "Lưu phiếu nhập thành công");
        } catch (Exception e) {
            DialogHelper.alert(this, "Lưu phiếu nhập thất bại");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdatePNActionPerformed

    private void jpnSoLuongPNPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jpnSoLuongPNPropertyChange
        try {
            int soLuong = jpnSoLuongPN.getValue();
            double donGia = Double.parseDouble(lblDonGiaPN.getText());
            double thanhTien = soLuong * donGia;

            txtThanhTienPN.setText(String.valueOf(thanhTien));
        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnSoLuongPNPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhieuNhapJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletePN;
    private javax.swing.JButton btnInsertPN;
    private javax.swing.JButton btnNewPN;
    private javax.swing.JButton btnUpdatePN;
    private javax.swing.JComboBox<String> cboMaNvPN;
    private javax.swing.JComboBox<String> cboMaXePN;
    private javax.swing.JComboBox<String> cboNhaccPN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.calendar.JDateChooser jpnNgayNhapPN;
    private com.toedter.components.JSpinField jpnSoLuongPN;
    private javax.swing.JLabel lblDonGiaPN;
    private javax.swing.JLabel lblMauXePN;
    private javax.swing.JLabel lblTenNvPN;
    private javax.swing.JLabel lblTenXePN;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JMenuItem mnuDangNhap;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuDoiMatKhau;
    private javax.swing.JMenuItem mnuThoat;
    private javax.swing.JTable tblPhieuNhap;
    private javax.swing.JTextField txtMaPN;
    private javax.swing.JTextField txtThanhTienPN;
    private javax.swing.JTextField txtTimKiemPN;
    private javax.swing.JTextField txtTongTienPN;
    // End of variables declaration//GEN-END:variables

    void init(){
        setIconImage(ImageHelper.getAppIcon());
        setLocationRelativeTo(null);
        fillCboMaNV();
        fillNhacc();
        fillCboMaXe();
        initMaPN();
        DefaultTableModel model = (DefaultTableModel) tblPhieuNhap.getModel();
        model.setRowCount(0);
    }
    
    void fillCboMaNV(){
        DefaultComboBoxModel model = (DefaultComboBoxModel)cboMaNvPN.getModel();
        model.removeAllElements();
        List<NhanVien> list = nvDAO.selectAll();
        for (NhanVien nv : list) {
            model.addElement(nv.getMaNv());
        }
    }
    
    void selectMaNV(){
        String nhanVien = (String) cboMaNvPN.getSelectedItem();
        if (nhanVien != null) {
            NhanVien nv = nvDAO.selectById(nhanVien);
        lblTenNvPN.setText(nv.getHoTen());
        }  
    }
    
    void fillNhacc(){
        DefaultComboBoxModel model = (DefaultComboBoxModel)cboNhaccPN.getModel();
        model.removeAllElements();
        List<NhaCungCap> list = nccDAO.selectAll();
        for (NhaCungCap ncc : list) {
            model.addElement(ncc.getMaNcc());
        }
    }
    
    void fillCboMaXe(){
        DefaultComboBoxModel model = (DefaultComboBoxModel)cboMaXePN.getModel();
        model.removeAllElements();
            List<Xe> list = xeDAO.selectAll();
            for (Xe xe : list) {
                model.addElement(xe.getMaXe());
            }
    }
   
    
    void selectMaXe(){
        String maXe = (String) cboMaXePN.getSelectedItem();
        if (maXe != null) {
            Xe xe = xeDAO.selectById(maXe);
            
            lblTenXePN.setText(xe.getTenXe());
            lblDonGiaPN.setText(String.valueOf(xe.getGiaNhap()));
            lblMauXePN.setText(xe.getMaMau());
        }
    }
    
    void insertPN() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblPhieuNhap.getModel();
            String maPhieuNhap = txtMaPN.getText();
            String tenXe = lblTenXePN.getText();
            String maxe = (String) cboMaXePN.getSelectedItem();
            String mauXe = lblMauXePN.getText();
            String ncc = (String) cboNhaccPN.getSelectedItem();
            int soLuong = (int) jpnSoLuongPN.getValue();
            Double donGia = Double.parseDouble(lblDonGiaPN.getText());
            Double thanhTien = Double.parseDouble(txtThanhTienPN.getText());
            Object[] row = {maPhieuNhap, maxe, tenXe, mauXe, soLuong, ncc, donGia, thanhTien};
            model.addRow(row);
            double tt = Double.parseDouble(txtTongTienPN.getText());
            txtTongTienPN.setText(String.valueOf(tt + thanhTien));  
            
        } catch (Exception e) {
        }
    }
    
    void updatePN(){
        
    }
    
    void deletePN(){
        try {
                for (int row : tblPhieuNhap.getSelectedRows()) {
              String mapn =  (String) tblPhieuNhap.getValueAt(row, 0);
              pnDAO.delete(mapn);
          }
        } catch (Exception e) {
        }
    }
    
    void deletePNCT(){
        try {
                for (int row : tblPhieuNhap.getSelectedRows()) {
              String mapnct =  (String) tblPhieuNhap.getValueAt(row, 0);
              pnctDAO.delete(mapnct);
              
          }
                deleteSoLuongXe();
        } catch (Exception e) {
        }
    }

    void luuPN() {
        try {
            PhieuNhap pn = new PhieuNhap();
            pn.setMaPhieuNhap(txtMaPN.getText());
            pn.setMaNv(String.valueOf(cboMaNvPN.getSelectedItem()));
            pn.setMaNcc(String.valueOf(cboNhaccPN.getSelectedItem()));
            pn.setNgayNhap(jpnNgayNhapPN.getDate());
            pn.setTongTien(Double.parseDouble(txtThanhTienPN.getText()));
            pnDAO.insert(pn);
        } catch (Exception e) {
        }
    }
    
    void luuPNCT() {
        try {
            PhieuNhapChiTiet pnct = new PhieuNhapChiTiet();
            int n = tblPhieuNhap.getRowCount();
            for (int i = 0; i < n; i++) {
                pnct.setMaPhieuNhap((String) tblPhieuNhap.getValueAt(i, 0));
                pnct.setMaXe((String) tblPhieuNhap.getValueAt(i, 1));
                pnct.setSoLuong((int) tblPhieuNhap.getValueAt(i, 4));
                pnct.setGiaNhap((double)(tblPhieuNhap.getValueAt(i, 6)));
                pnctDAO.insert(pnct);
                xeDAO.updateSoLuongPN(pnct.getMaXe(), pnct.getSoLuong());
            }    
            
            
        } catch (Exception e) {
        }
    }
    
    void deleteSoLuongXe() {
        try {
            PhieuNhapChiTiet pnct = new PhieuNhapChiTiet();
            int n = tblPhieuNhap.getRowCount();
            for (int i = 0; i < n; i++) {
                pnct.setMaPhieuNhap((String) tblPhieuNhap.getValueAt(i, 0));
                pnct.setMaXe((String) tblPhieuNhap.getValueAt(i, 1));
                pnct.setSoLuong((int) tblPhieuNhap.getValueAt(i, 4));
                pnct.setGiaNhap((double)(tblPhieuNhap.getValueAt(i, 6)));
                
                xeDAO.updateSoLuong(pnct.getMaXe(), pnct.getSoLuong());
            }    
            
            
        } catch (Exception e) {
        }
    }
    
    void initMaPN() {
        Date c = DateHelper.now();
        String b = DateHelper.toString(c, "yyyyMMddHHmmss");
        txtMaPN.setText("PN" + b);
    }
    
    void clear(){
        DefaultTableModel model = (DefaultTableModel) tblPhieuNhap.getModel();
        model.setRowCount(0);
        initMaPN();
        jpnSoLuongPN.setValue(0);
        cboMaNvPN.setSelectedIndex(0);
        cboMaXePN.setSelectedIndex(0);
        cboNhaccPN.setSelectedIndex(0);
        txtTongTienPN.setText("0");
        txtTimKiemPN.setText("");
    }
    //a
    void clearTablePN() {
        DefaultTableModel model = (DefaultTableModel) tblPhieuNhap.getModel();
        int i = tblPhieuNhap.getSelectedRow();
        double tt = Double.parseDouble(txtTongTienPN.getText());
        double thanhTien = (double) tblPhieuNhap.getValueAt(i, 7);
        txtTongTienPN.setText(String.valueOf(tt - thanhTien));
        model.removeRow(i);
    }
    
    void timKiemTheoMaHD(){
        
        String maPN = txtTimKiemPN.getText();
        if (maPN != null) {  
            PhieuNhap pn = pnDAO.selectById(maPN);
            List<PhieuNhapChiTiet> listPNCT = pnctDAO.selectByMaPN(maPN);    
            DefaultTableModel model2 = (DefaultTableModel) tblPhieuNhap.getModel();
            model2.setRowCount(0);
            for (PhieuNhapChiTiet pnct : listPNCT) {
                Xe xe = xeDAO.selectById(pnct.getMaXe());
                Object[] row = {pnct.getMaPhieuNhap(),pnct.getMaXe(),xe.getTenXe(),xe.getMaMau(),pnct.getSoLuong(),pn.getMaNcc(),pnct.getGiaNhap(),pnct.getSoLuong()*pnct.getGiaNhap()};
                model2.addRow(row);
                double tt = Double.parseDouble(txtTongTienPN.getText());
                txtTongTienPN.setText(String.valueOf(tt + (pnct.getSoLuong()*pnct.getGiaNhap())));
            }
            
        }
    }
    
    boolean check(){
        if (jpnSoLuongPN.getValue() == 0) {
            
        }
        return true;
    }
}
