/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.KhachHangDAO;
import DAO.MauXeDAO;
import DAO.NhanVienDAO;
import DAO.PhieuXuatChiTietDAO;
import DAO.PhieuXuatDAO;
import DAO.XeDAO;
import entity.KhachHang;
import entity.MauXe;
import entity.NhanVien;
import entity.PhieuXuat;
import entity.PhieuXuatChiTiet;
import entity.Xe;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import utils.Auth;
import utils.DateHelper;
import utils.DialogHelper;
import utils.ImageHelper;

/**
 *
 * @author ADMIN
 */
public class PhieuXuatJframe extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public PhieuXuatJframe() {
        initComponents();
        init();
    }
    MauXeDAO mauXeDAO = new MauXeDAO();
    XeDAO xeDAO = new XeDAO();
    NhanVienDAO nhanVienDAO = new NhanVienDAO();
    KhachHangDAO khachHangDAO = new KhachHangDAO();
    PhieuXuatChiTietDAO pxctDAO = new PhieuXuatChiTietDAO();
    PhieuXuatDAO pxDAO = new PhieuXuatDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnToolbar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lblstatus = new javax.swing.JLabel();
        pnMain = new javax.swing.JPanel();
        lblHoaDonBanHang = new javax.swing.JLabel();
        pnThongTinBanHang = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboNhanVien = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cboKhachHang = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtSdtKH = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtDiaChiKH = new javax.swing.JTextField();
        pnHoaDonChiTiet = new javax.swing.JPanel();
        pnTtSP = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cboMauXe = new javax.swing.JComboBox<>();
        jPanel23 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtTenXe = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtSoLuongCon = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cboMaXe = new javax.swing.JComboBox<>();
        jPanel25 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        spinSoLuong = new com.toedter.components.JSpinField();
        lblDonGia = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        pnButton = new javax.swing.JPanel();
        btnTaoMoiHD = new javax.swing.JButton();
        btnLuuHD = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        pnTimKiem = new javax.swing.JPanel();
        txtTimMaHoaDon = new javax.swing.JTextField();
        btnTimMaHoaDon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cboMaHoaDon = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuDangNhap = new javax.swing.JMenuItem();
        mnuDangXuat = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuThoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý bán hàng");
        setBackground(new java.awt.Color(195, 199, 198));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 874));

        pnToolbar.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jButton1.setText("Sản phẩm");
        pnToolbar.add(jButton1);

        jButton2.setText("Hóa đơn");
        pnToolbar.add(jButton2);

        jButton3.setText("Nhập hàng");
        pnToolbar.add(jButton3);

        jButton4.setText("Thống kê");
        pnToolbar.add(jButton4);

        jButton8.setText("Admin");
        pnToolbar.add(jButton8);

        jButton5.setText("Đổi mật khẩu");
        pnToolbar.add(jButton5);

        jButton6.setText("Đăng xuất");
        pnToolbar.add(jButton6);

        jButton7.setText("Thoát");
        pnToolbar.add(jButton7);

        lblstatus.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(26, 167, 238));
        lblstatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblstatus.setText("jLabel1");

        pnMain.setPreferredSize(new java.awt.Dimension(1200, 766));

        lblHoaDonBanHang.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblHoaDonBanHang.setForeground(new java.awt.Color(227, 106, 121));
        lblHoaDonBanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoaDonBanHang.setText("HÓA ĐƠN BÁN HÀNG");
        lblHoaDonBanHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 82, 134), 1, true));
        lblHoaDonBanHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pnThongTinBanHang.setPreferredSize(new java.awt.Dimension(1000, 217));
        pnThongTinBanHang.setLayout(new java.awt.GridLayout(1, 2, 40, 0));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin bên bán", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 16))); // NOI18N
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(4, 1));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(59, 82, 134));
        jLabel9.setText("Mã hóa đơn");
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 49));

        txtMaHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaHoaDon.setForeground(new java.awt.Color(59, 82, 134));
        txtMaHoaDon.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMaHoaDon.setEnabled(false);
        jPanel11.add(txtMaHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 390, 30));

        jPanel6.add(jPanel11);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(59, 82, 134));
        jLabel2.setText("Ngày bán");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 49));

        jDateChooser1.setForeground(new java.awt.Color(59, 82, 134));
        jDateChooser1.setDateFormatString("MMMMM dd, yyyy");
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel9.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 9, 390, 30));

        jPanel6.add(jPanel9);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(59, 82, 134));
        jLabel3.setText("Mã nhân viên");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 49));

        cboNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboNhanVien.setForeground(new java.awt.Color(59, 82, 134));
        cboNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNhanVien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNhanVienItemStateChanged(evt);
            }
        });
        cboNhanVien.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboNhanVienPropertyChange(evt);
            }
        });
        jPanel8.add(cboNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 390, 30));

        jPanel6.add(jPanel8);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(59, 82, 134));
        jLabel4.setText("Tên nhân viên");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 49));

        txtTenNV.setEditable(false);
        txtTenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenNV.setForeground(new java.awt.Color(59, 82, 134));
        txtTenNV.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenNV.setText("jTextField1");
        txtTenNV.setEnabled(false);
        jPanel10.add(txtTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 390, 30));

        jPanel6.add(jPanel10);

        pnThongTinBanHang.add(jPanel6);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin bên mua", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 16))); // NOI18N
        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.GridLayout(4, 1));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(59, 82, 134));
        jLabel11.setText("Mã khách hàng");
        jPanel14.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 49));

        cboKhachHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboKhachHang.setForeground(new java.awt.Color(59, 82, 134));
        cboKhachHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKhachHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboKhachHangItemStateChanged(evt);
            }
        });
        cboKhachHang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboKhachHangPropertyChange(evt);
            }
        });
        jPanel14.add(cboKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 390, 30));

        jPanel12.add(jPanel14);

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(59, 82, 134));
        jLabel12.setText("Tên khách hàng");
        jPanel15.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 49));

        txtTenKH.setEditable(false);
        txtTenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenKH.setForeground(new java.awt.Color(59, 82, 134));
        txtTenKH.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenKH.setText("jTextField1");
        txtTenKH.setEnabled(false);
        jPanel15.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 390, 30));

        jPanel12.add(jPanel15);

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(59, 82, 134));
        jLabel13.setText("Số điện thoại");
        jPanel16.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 49));

        txtSdtKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSdtKH.setForeground(new java.awt.Color(59, 82, 134));
        txtSdtKH.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSdtKH.setEnabled(false);
        jPanel16.add(txtSdtKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 390, 30));

        jPanel12.add(jPanel16);

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(59, 82, 134));
        jLabel14.setText("Địa chỉ");
        jPanel17.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 49));

        txtDiaChiKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDiaChiKH.setForeground(new java.awt.Color(59, 82, 134));
        txtDiaChiKH.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDiaChiKH.setEnabled(false);
        jPanel17.add(txtDiaChiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 390, 30));

        jPanel12.add(jPanel17);

        pnThongTinBanHang.add(jPanel12);

        pnHoaDonChiTiet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin các sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 16))); // NOI18N
        pnHoaDonChiTiet.setForeground(new java.awt.Color(59, 82, 134));
        pnHoaDonChiTiet.setOpaque(false);

        pnTtSP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 82, 134), 1, true));
        pnTtSP.setLayout(new java.awt.GridLayout(2, 0));

        jPanel18.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(59, 82, 134));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Màu xe");
        jLabel5.setToolTipText("");

        cboMauXe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboMauXe.setForeground(new java.awt.Color(59, 82, 134));
        cboMauXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMauXe.setToolTipText("");
        cboMauXe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMauXeItemStateChanged(evt);
            }
        });
        cboMauXe.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboMauXePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addComponent(cboMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel18.add(jPanel20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(59, 82, 134));
        jLabel10.setText("Tên xe");
        jLabel10.setToolTipText("");

        txtTenXe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenXe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTenXe.setEnabled(false);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(txtTenXe, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel18.add(jPanel23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(59, 82, 134));
        jLabel6.setText("Trong kho còn");
        jLabel6.setToolTipText("");

        txtSoLuongCon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSoLuongCon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSoLuongCon.setText("jTextField4");
        txtSoLuongCon.setEnabled(false);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSoLuongCon, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuongCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel18.add(jPanel24);

        pnTtSP.add(jPanel18);

        jPanel19.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(59, 82, 134));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mã xe");
        jLabel7.setToolTipText("");

        cboMaXe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboMaXe.setForeground(new java.awt.Color(59, 82, 134));
        cboMaXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMaXe.setToolTipText("");
        cboMaXe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMaXeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addComponent(cboMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel19.add(jPanel22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(59, 82, 134));
        jLabel8.setText("Số lượng");
        jLabel8.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(59, 82, 134));
        jLabel17.setText("Đơn giá");
        jLabel17.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(59, 82, 134));
        jLabel18.setText("X");
        jLabel18.setToolTipText("");

        spinSoLuong.setToolTipText("");
        spinSoLuong.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spinSoLuongPropertyChange(evt);
            }
        });

        lblDonGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDonGia.setForeground(new java.awt.Color(59, 82, 134));
        lblDonGia.setText("jLabel21");
        lblDonGia.setToolTipText("");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(spinSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(lblDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spinSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel19.add(jPanel25);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(59, 82, 134));
        jLabel15.setText("Thành tiền");
        jLabel15.setToolTipText("");

        txtThanhTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtThanhTien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtThanhTien.setText("jTextField5");
        txtThanhTien.setEnabled(false);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtThanhTien, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel19.add(jPanel26);

        pnTtSP.add(jPanel19);

        jPanel21.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(26, 167, 238));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel21.add(btnThem);

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(26, 167, 238));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel21.add(btnXoa);

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã xe", "Tên xe", "Màu xe", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.setToolTipText("Nháy đúp vào hàng muốn xóa để xóa");
        tblSanPham.setRowHeight(25);
        tblSanPham.setRowMargin(4);
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(59, 82, 134));
        jLabel16.setText("Tổng tiền");

        txtTongTien.setEditable(false);
        txtTongTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTongTien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTongTien.setText("0.0");
        txtTongTien.setEnabled(false);

        pnButton.setLayout(new java.awt.GridLayout(1, 0));

        btnTaoMoiHD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTaoMoiHD.setForeground(new java.awt.Color(26, 167, 238));
        btnTaoMoiHD.setText("Tạo mới hóa đơn");
        btnTaoMoiHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiHDActionPerformed(evt);
            }
        });
        pnButton.add(btnTaoMoiHD);

        btnLuuHD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuuHD.setForeground(new java.awt.Color(26, 167, 238));
        btnLuuHD.setText("Lưu hóa đơn");
        btnLuuHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuHDActionPerformed(evt);
            }
        });
        pnButton.add(btnLuuHD);

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(26, 167, 238));
        jButton14.setText("Cập nhật hóa đơn");
        pnButton.add(jButton14);

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(26, 167, 238));
        jButton13.setText("In hóa đơn");
        pnButton.add(jButton13);

        javax.swing.GroupLayout pnHoaDonChiTietLayout = new javax.swing.GroupLayout(pnHoaDonChiTiet);
        pnHoaDonChiTiet.setLayout(pnHoaDonChiTietLayout);
        pnHoaDonChiTietLayout.setHorizontalGroup(
            pnHoaDonChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHoaDonChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnHoaDonChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnHoaDonChiTietLayout.createSequentialGroup()
                        .addComponent(pnTtSP, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHoaDonChiTietLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnHoaDonChiTietLayout.setVerticalGroup(
            pnHoaDonChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHoaDonChiTietLayout.createSequentialGroup()
                .addGroup(pnHoaDonChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnTtSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnHoaDonChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(pnButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        txtTimMaHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimMaHoaDon.setForeground(new java.awt.Color(209, 209, 209));
        txtTimMaHoaDon.setText("Nhập mã hóa đơn");
        txtTimMaHoaDon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimMaHoaDonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimMaHoaDonFocusLost(evt);
            }
        });

        btnTimMaHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTimMaHoaDon.setForeground(new java.awt.Color(59, 82, 134));
        btnTimMaHoaDon.setText("Tìm kiếm");
        btnTimMaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimMaHoaDonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(59, 82, 134));
        jLabel1.setText("Mã hóa đơn");

        cboMaHoaDon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnTimKiemLayout = new javax.swing.GroupLayout(pnTimKiem);
        pnTimKiem.setLayout(pnTimKiemLayout);
        pnTimKiemLayout.setHorizontalGroup(
            pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cboMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimMaHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        pnTimKiemLayout.setVerticalGroup(
            pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimKiemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimMaHoaDon)
                    .addComponent(jLabel1)
                    .addComponent(cboMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHoaDonBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnHoaDonChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnThongTinBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(pnTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addComponent(lblHoaDonBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnThongTinBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnHoaDonChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblstatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 820, Short.MAX_VALUE))
        );

        jMenu1.setText("Hệ thống");

        mnuDangNhap.setText("Đăng nhập");
        jMenu1.add(mnuDangNhap);

        mnuDangXuat.setText("Đăng xuất");
        jMenu1.add(mnuDangXuat);
        jMenu1.add(jSeparator2);

        mnuDoiMatKhau.setText("Đổi mật khẩu");
        jMenu1.add(mnuDoiMatKhau);
        jMenu1.add(jSeparator1);

        mnuThoat.setText("Thoát");
        jMenu1.add(mnuThoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        jMenuItem1.setText("Sản phẩm");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Nhân viên");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Khách hàng");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Nhà cung cấp");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Thống kê");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Trợ giúp");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimMaHoaDonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimMaHoaDonFocusGained
        if (txtTimMaHoaDon.getText().trim().equals("Nhập mã hóa đơn")) {
            txtTimMaHoaDon.setText("");
        }
        txtTimMaHoaDon.setForeground(new Color(59, 82, 134));
    }//GEN-LAST:event_txtTimMaHoaDonFocusGained

    private void txtTimMaHoaDonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimMaHoaDonFocusLost
        // TODO add your handling code here:
        if (txtTimMaHoaDon.getText().trim().equals("")) {
            txtTimMaHoaDon.setText("Nhập mã hóa đơn");
            txtTimMaHoaDon.setForeground(new Color(209, 209, 209));
        }
    }//GEN-LAST:event_txtTimMaHoaDonFocusLost

    private void cboMauXeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMauXeItemStateChanged
        try {
            this.fillCboMaXe();
            spinSoLuong.setValue(1);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboMauXeItemStateChanged

    private void cboMauXePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboMauXePropertyChange
        // TODO add your handling code here:
        try {
            this.fillCboMauxe();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboMauXePropertyChange

    private void cboMaXeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMaXeItemStateChanged
        // TODO add your handling code here:
        try {
            spinSoLuong.setValue(1);
            this.setThongTinXe();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboMaXeItemStateChanged

    private void spinSoLuongPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spinSoLuongPropertyChange
        // TODO add your handling code here:
        try {
            double donGia = Double.parseDouble(lblDonGia.getText());
            int soLuong = spinSoLuong.getValue();
            txtThanhTien.setText(String.valueOf(donGia * soLuong));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_spinSoLuongPropertyChange

    private void cboNhanVienPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboNhanVienPropertyChange
        // TODO add your handling code here:
        try {
            this.fillCboNhanVien();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboNhanVienPropertyChange

    private void cboKhachHangPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboKhachHangPropertyChange
        // TODO add your handling code here:
        try {
            this.fillCboKhachHang();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboKhachHangPropertyChange

    private void cboNhanVienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNhanVienItemStateChanged
        // TODO add your handling code here:
        try {
            this.setThongTinNhanVien();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboNhanVienItemStateChanged

    private void cboKhachHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboKhachHangItemStateChanged
        // TODO add your handling code here:
        try {
            this.setThongTinKhachHang();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboKhachHangItemStateChanged

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        themSP();
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.xoaSP();
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            this.xoaSP();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTaoMoiHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiHDActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnTaoMoiHDActionPerformed

    private void btnLuuHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuHDActionPerformed
        // TODO add your handling code here:
        try {
            this.luuHoaDon();
            this.luuHoaDonChiTiet();
            clear();
            DialogHelper.alert(this, "Lưu hóa đơn thành công!!!");
            this.fillCboMaHD();
        } catch (Exception e) {
            DialogHelper.alert(this, "Lưu hóa đơn không thành công!!!");
        }
    }//GEN-LAST:event_btnLuuHDActionPerformed

    private void btnTimMaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimMaHoaDonActionPerformed
        // TODO add your handling code here:
        this.timKiemTheoMaHD();
    }//GEN-LAST:event_btnTimMaHoaDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuXuatJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuXuatJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuXuatJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuXuatJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhieuXuatJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuHD;
    private javax.swing.JButton btnTaoMoiHD;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimMaHoaDon;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboKhachHang;
    private javax.swing.JComboBox<String> cboMaHoaDon;
    private javax.swing.JComboBox<String> cboMaXe;
    private javax.swing.JComboBox<String> cboMauXe;
    private javax.swing.JComboBox<String> cboNhanVien;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblHoaDonBanHang;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JMenuItem mnuDangNhap;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuDoiMatKhau;
    private javax.swing.JMenuItem mnuThoat;
    private javax.swing.JPanel pnButton;
    private javax.swing.JPanel pnHoaDonChiTiet;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnThongTinBanHang;
    private javax.swing.JPanel pnTimKiem;
    private javax.swing.JPanel pnToolbar;
    private javax.swing.JPanel pnTtSP;
    private com.toedter.components.JSpinField spinSoLuong;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtDiaChiKH;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtSdtKH;
    private javax.swing.JTextField txtSoLuongCon;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTenXe;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTimMaHoaDon;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
    private void init() {
        this.setLocationRelativeTo(null);
        this.setIconImage(ImageHelper.getAppIcon());
        lblstatus.setText("Xin chào :" + Auth.user + ". Hôm nay, " + DateHelper.toString(DateHelper.now(), "dd - MM - yyyy ") + ". Chúc bạn một ngày làm việc tốt lành!!!!!!!  ");
        initMaHoaDon();
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        fillCboMaHD();
    }

    private void initMaHoaDon() {
        Date c = DateHelper.now();
        String b = DateHelper.toString(c, "yyyyMMddHHmmss");
        txtMaHoaDon.setText("HD" + b);
    }

    private void fillCboMauxe() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMauXe.getModel();
        model.removeAllElements();
        List<MauXe> list = mauXeDAO.selectAll();
        for (MauXe mauXe : list) {
            model.addElement(mauXe.getMaMau());
        }
    }

    private void fillCboMaXe() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMaXe.getModel();
        model.removeAllElements();
        String mauXe = (String) cboMauXe.getSelectedItem();
        if (mauXe != null) {
            List<Xe> list = xeDAO.selectByMauXe(mauXe);
            for (Xe xe : list) {
                model.addElement(xe.getMaXe());
            }
        }
    }

    private void setThongTinXe() {
        String maXe = (String) cboMaXe.getSelectedItem();
        if (maXe != null) {
            Xe xe = xeDAO.selectById(maXe);
            txtTenXe.setText(xe.getTenXe());
            txtSoLuongCon.setText(String.valueOf(xe.getSoLuong()));
            spinSoLuong.setMaximum(xe.getSoLuong());
            lblDonGia.setText(String.valueOf(xe.getGiaBan()));
        }
    }

    private void fillCboNhanVien() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboNhanVien.getModel();
        model.removeAllElements();
        List<NhanVien> list = nhanVienDAO.selectAll();
        for (NhanVien nv : list) {
            model.addElement(nv.getMaNv());
        }
    }

    private void fillCboKhachHang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboKhachHang.getModel();
        model.removeAllElements();
        List<KhachHang> list = khachHangDAO.selectAll();
        for (KhachHang kh : list) {
            model.addElement(kh.getMaKh());
        }
    }

    private void setThongTinNhanVien() {
        String maNv = (String) cboNhanVien.getSelectedItem();
        if (maNv != null) {
            NhanVien nv = nhanVienDAO.selectById(maNv);
            txtTenNV.setText(nv.getHoTen());
        }
    }

    private void setThongTinKhachHang() {
        String maKh = (String) cboKhachHang.getSelectedItem();
        if (maKh != null) {
            KhachHang kh = khachHangDAO.selectById(maKh);
            txtTenKH.setText(kh.getHoTen());
            txtSdtKH.setText(kh.getSoDt());
            txtDiaChiKH.setText(kh.getDiaChi());
        }
    }

    private void themSP() {
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        String maXe = (String) cboMaXe.getSelectedItem();
        String tenXe = txtTenXe.getText();
        String mauXe = (String) cboMauXe.getSelectedItem();
        int soLuong = spinSoLuong.getValue();
        Double donGia = Double.parseDouble(lblDonGia.getText());
        Double thanhTien = Double.parseDouble(txtThanhTien.getText());
        Object[] row = {maXe, tenXe, mauXe, soLuong, donGia, thanhTien};
        model.addRow(row);
        double tt = Double.parseDouble(txtTongTien.getText());
        txtTongTien.setText(String.valueOf(tt + thanhTien));
    }

    private void xoaSP() {
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        int i = tblSanPham.getSelectedRow();
        double tt = Double.parseDouble(txtTongTien.getText());
        double thanhTien = (double) tblSanPham.getValueAt(i, 5);
        txtTongTien.setText(String.valueOf(tt - thanhTien));
        model.removeRow(i);
    }

    private void luuHoaDon() {
        try {
            PhieuXuat px = new PhieuXuat();
            px.setMaPhieuXuat(txtMaHoaDon.getText());
            px.setMaNv(String.valueOf(cboNhanVien.getSelectedItem()));
            px.setMaKh(String.valueOf(cboKhachHang.getSelectedItem()));
            px.setNgayXuat(jDateChooser1.getDate());
            px.setTongTien(Double.parseDouble(txtTongTien.getText()));
            pxDAO.insert(px);
        } catch (Exception e) {
        }

    }

    private void luuHoaDonChiTiet() {
        try {
            int n = tblSanPham.getRowCount();
            for (int i = 0; i < n; i++) {
                PhieuXuatChiTiet pxct = new PhieuXuatChiTiet();
                pxct.setMaPhieuXuat(txtMaHoaDon.getText());
                pxct.setMaXe((String) tblSanPham.getValueAt(i, 0));
                pxct.setGiaXuat((double) tblSanPham.getValueAt(i, 4));
                pxct.setSoLuong((int) tblSanPham.getValueAt(i, 3));
                pxctDAO.insert(pxct);
                xeDAO.updateSoLuong(pxct.getMaXe(), pxct.getSoLuong());
            }
        } catch (Exception e) {
        }
    }
    private void clear(){
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        initMaHoaDon();
        cboKhachHang.setSelectedIndex(0);
        cboNhanVien.setSelectedIndex(0);
    }
    private void fillCboMaHD(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMaHoaDon.getModel();
        model.removeAllElements();
        List<PhieuXuat> list = pxDAO.selectAll();
        for (PhieuXuat px : list) {
            model.addElement(px.getMaPhieuXuat());
        }
    }
    
    private void timKiemTheoMaHD(){
        String maHD = (String) cboMaHoaDon.getSelectedItem();
        if (maHD!= null) {
            PhieuXuat px = pxDAO.selectById(maHD);
            List<PhieuXuatChiTiet> listPXCT = pxctDAO.selectByMaPX(maHD);
            // set thông tin phiếu xuất
            txtMaHoaDon.setText(px.getMaPhieuXuat());
            jDateChooser1.setDate(px.getNgayXuat());
                //fill lại cbo nhanvien
            NhanVien nv = nhanVienDAO.selectById(px.getMaNv());
            DefaultComboBoxModel model = (DefaultComboBoxModel) cboNhanVien.getModel();
            model.removeAllElements();
            model.addElement(nv.getMaNv());
                //fill lại cbo khachhang
            KhachHang kh = khachHangDAO.selectById(px.getMaKh());
            DefaultComboBoxModel model1 = (DefaultComboBoxModel) cboKhachHang.getModel();
            model1.removeAllElements();
            model1.addElement(kh.getMaKh());
            
            // set thông tin phiếu xuất chi tiết
            DefaultTableModel model2 = (DefaultTableModel) tblSanPham.getModel();
            model2.setRowCount(0);
            for (PhieuXuatChiTiet pxct : listPXCT) {
                Xe xe = xeDAO.selectById(pxct.getMaXe());
                Object[] row = {pxct.getMaXe(),xe.getTenXe(),xe.getMaMau(),pxct.getSoLuong(),pxct.getGiaXuat(),pxct.getSoLuong()*pxct.getGiaXuat()};
                model2.addRow(row);
                txtTongTien.setText(String.valueOf(px.getTongTien()));
            }
            
        }
    }
}
