/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.HangXeDAO;
import DAO.MauXeDAO;
import DAO.XeDAO;
import entity.HangXe;
import entity.MauXe;
import entity.Xe;
import java.io.File;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import utils.Auth;
import utils.DateHelper;
import utils.DialogHelper;
import utils.ImageHelper;

/**
 *
 * @author ADMIN
 */
public class Xemay extends javax.swing.JFrame {

    JFileChooser fileChooser = new JFileChooser("C:/Users/PC/Documents/NetBeansProjects/PolyProject1/src/imagesBy");
    XeDAO xeDAO = new XeDAO();
    HangXeDAO hxDAO = new HangXeDAO();
    MauXeDAO mxDAO = new MauXeDAO();
    int row = -1;
    /**
     * Creates new form mainForm
     */
    public Xemay() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lblstatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        cboHangXe = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblXemay = new javax.swing.JTable();
        btnDs = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaxe = new javax.swing.JTextField();
        txtTenxe = new javax.swing.JTextField();
        txtSoluong = new javax.swing.JTextField();
        txtGianhap = new javax.swing.JTextField();
        txtGiaban = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        cboMamau = new javax.swing.JComboBox<>();
        cboMahang = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuDangNhap = new javax.swing.JMenuItem();
        mnuDangXuat = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuThoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý bán hàng");
        setBackground(new java.awt.Color(195, 199, 198));
        setPreferredSize(new java.awt.Dimension(1200, 900));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(195, 199, 198));

        jPanel2.setBackground(new java.awt.Color(195, 199, 198));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jButton1.setText("Sản phẩm");
        jPanel2.add(jButton1);

        jButton2.setText("Hóa đơn");
        jPanel2.add(jButton2);

        jButton3.setText("Nhập hàng");
        jPanel2.add(jButton3);

        jButton4.setText("Thống kê");
        jPanel2.add(jButton4);

        jButton8.setText("Admin");
        jPanel2.add(jButton8);

        jButton5.setText("Đổi mật khẩu");
        jPanel2.add(jButton5);

        jButton6.setText("Đăng xuất");
        jPanel2.add(jButton6);

        jButton7.setText("Thoát");
        jPanel2.add(jButton7);

        lblstatus.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(26, 167, 238));
        lblstatus.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("QUẢN LÝ XE MÁY");

        jTabbedPane1.setForeground(new java.awt.Color(255, 0, 0));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cboHangXe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cboHangXe.setForeground(new java.awt.Color(0, 51, 255));
        cboHangXe.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 0), new java.awt.Color(0, 204, 0)));
        cboHangXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHangXeActionPerformed(evt);
            }
        });

        tblXemay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblXemay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã xe", "Tên xe", "Mã  màu", "Mã hãng", "Số lượng", "Giá nhập", "Giá bán", "Hình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblXemay.setGridColor(new java.awt.Color(255, 0, 0));
        tblXemay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblXemayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblXemay);

        btnDs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDs.setForeground(new java.awt.Color(255, 51, 51));
        btnDs.setText("Danh sách xe máy");
        btnDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(cboHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDs, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDs, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Danh mục xe máy", jPanel3);

        lblHinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Mã xe :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Tên xe :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("Mã màu :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Mã hãng :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Số lượng :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("Giá nhập :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Giá bán :");

        txtMaxe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        txtTenxe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        txtSoluong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        txtGianhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        txtGiaban.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 8, 10));

        btnFirst.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        jPanel5.add(btnFirst);

        btnPrev.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        jPanel5.add(btnPrev);

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel5.add(btnNext);

        btnLast.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        jPanel5.add(btnLast);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 8, 0));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 51, 0));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel6.add(btnThem);

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 51, 0));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel6.add(btnSua);

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 51, 0));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel6.add(btnXoa);

        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMoi.setForeground(new java.awt.Color(255, 51, 0));
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        jPanel6.add(btnMoi);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGianhap, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboMahang, javax.swing.GroupLayout.Alignment.TRAILING, 0, 500, Short.MAX_VALUE)
                    .addComponent(cboMamau, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenxe, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaxe, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGiaban, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaxe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboMamau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMahang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGianhap, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaban, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Xe máy", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(849, 849, 849))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblstatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Hệ thống");

        mnuDangNhap.setText("Đăng nhập");
        jMenu1.add(mnuDangNhap);

        mnuDangXuat.setText("Đăng xuất");
        jMenu1.add(mnuDangXuat);
        jMenu1.add(jSeparator2);

        mnuDoiMatKhau.setText("Đổi mật khẩu");
        jMenu1.add(mnuDoiMatKhau);
        jMenu1.add(jSeparator1);

        mnuThoat.setText("Thoát");
        jMenu1.add(mnuThoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        jMenuItem1.setText("Sản phẩm");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Nhân viên");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Khách hàng");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Nhà cung cấp");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Thống kê");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Trợ giúp");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(481, 481, 481))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblXemayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblXemayMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            this.row = tblXemay.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblXemayMouseClicked

    private void cboHangXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHangXeActionPerformed
        // TODO add your handling code here:
        this.fillTableByHangXe();
    }//GEN-LAST:event_cboHangXeActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
       if(check()){
           this.insert();
       }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if(check()){
            this.update();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        this.first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        // TODO add your handling code here:
        this.chonAnh();
    }//GEN-LAST:event_lblHinhMouseClicked

    private void btnDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsActionPerformed
        // TODO add your handling code here:
        this.filltable();
    }//GEN-LAST:event_btnDsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Xemay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Xemay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Xemay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Xemay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Xemay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDs;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboHangXe;
    private javax.swing.JComboBox<String> cboMahang;
    private javax.swing.JComboBox<String> cboMamau;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JMenuItem mnuDangNhap;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuDoiMatKhau;
    private javax.swing.JMenuItem mnuThoat;
    private javax.swing.JTable tblXemay;
    private javax.swing.JTextField txtGiaban;
    private javax.swing.JTextField txtGianhap;
    private javax.swing.JTextField txtMaxe;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTenxe;
    // End of variables declaration//GEN-END:variables
    private void init(){
        this.setLocationRelativeTo(null);
        this.setIconImage(ImageHelper.getAppIcon());
        lblstatus.setText("Xin chào :"+Auth.user+". Hôm nay, "+DateHelper.toString(DateHelper.now(), "dd - MM - yyyy ")+". Chúc bạn một ngày làm việc tốt lành!");
        this.fillComboBoxHangXe();
        this.fillComboBoxMamau();
        this.fillComboBoxMahang();
        this.filltable();
    }
    void fillComboBoxMamau(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMamau.getModel();
        model.removeAllElements();
        List<MauXe> list = mxDAO.selectAll();
        for(MauXe mx : list){
            model.addElement(mx);
        }
    }
    void fillComboBoxMahang(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMahang.getModel();
        model.removeAllElements();
        List<HangXe> list = hxDAO.selectAll();
        for(HangXe hx : list){
            model.addElement(hx);
        }
    }
    
    
    
    
    void chonAnh(){
        if(fileChooser.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            ImageHelper.save(file); // lưu hình vào thư mục
            ImageIcon icon = ImageHelper.read(file.getName());
            lblHinh.setIcon(icon);
            lblHinh.setToolTipText(file.getName());
        }
    }
    
    void filltable(){
        DefaultTableModel model = (DefaultTableModel) tblXemay.getModel();
        model.setRowCount(0);
        try{
            List<Xe> list = xeDAO.selectAll();
            for(Xe xe : list){
                Object[] row = {
                    xe.getMaXe(),
                    xe.getTenXe(),
                    xe.getMaMau(),
                    xe.getMaHang(),
                    xe.getSoLuong(),
                    xe.getGiaNhap(),
                    xe.getGiaBan(),
                    xe.getHinh()
                };
                model.addRow(row);
            }
        }catch(Exception e){
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }
    
    void setForm(entity.Xe xe){
        txtMaxe.setText(xe.getMaXe());
        txtTenxe.setText(xe.getTenXe());
        cboMamau.setSelectedItem(xe.getMaMau());
        cboMahang.setSelectedItem(xe.getMaHang());
        txtSoluong.setText(String.valueOf(xe.getSoLuong()));
        txtGianhap.setText(String.valueOf(xe.getGiaNhap()));
        txtGiaban.setText(String.valueOf(xe.getGiaBan()));
        if(xe.getHinh()!= null){
            lblHinh.setToolTipText(xe.getHinh());
            lblHinh.setIcon(ImageHelper.read(xe.getHinh()));
        }
    }
    
    entity.Xe getForm(){
        entity.Xe xe = new Xe();
        HangXe hx = (HangXe) cboMahang.getSelectedItem();
        MauXe mx = (MauXe) cboMamau.getSelectedItem();
        xe.setMaXe(txtMaxe.getText());
        xe.setTenXe(txtTenxe.getText());
        xe.setMaMau(mx.getMaMau());
        xe.setMaHang(hx.getMaHang());
        xe.setSoLuong(Integer.valueOf(txtSoluong.getText()));
        xe.setGiaNhap(Double.valueOf(txtGianhap.getText()));
        xe.setGiaBan(Double.valueOf(txtGiaban.getText()));
        xe.setHinh(lblHinh.getToolTipText());
        return xe;
    }
    
    void clearForm(){
        Xe xe = new Xe();
        this.setForm(xe);
        this.row = -1;
        this.updateStatus();
    }
    void edit(){
        String maxe = (String) tblXemay.getValueAt(this.row, 0);
        Xe xe = xeDAO.selectById(maxe);
        this.setForm(xe);
        jTabbedPane1.setSelectedIndex(1);
        this.updateStatus();
        
    }
    void insert(){
        Xe xe = getForm();
        try{
            xeDAO.insert(xe);
            this.filltable();
            this.clearForm();
            DialogHelper.alert(this, "thêm mới thành công");
        }catch(Exception e){
            DialogHelper.alert(this, "Thêm mới thất bại");
        }
    }
    void update(){
        Xe xe = getForm();
        try{
            xeDAO.update(xe);
            this.filltable();
            DialogHelper.alert(this, "Cập nhật thành công");
        }catch(Exception e){
            DialogHelper.alert(this, "Cập nhật thất bại");
        }
    }
    void delete(){
        if(!Auth.isManager()){
            DialogHelper.alert(this, "Bạn không có quyền xóa xe máy");
            
        }
        else{
            String maxe = txtMaxe.getText();
            try{
                xeDAO.delete(maxe);
                this.filltable();
                this.clearForm();
                DialogHelper.alert(this, "Xóa xe máy thành công");
            }catch(Exception e){
                DialogHelper.alert(this, "Xóa không thành công");
            }
        }
    }
    void first(){
        this.row =0;
        this.edit();
    }
    void prev(){
        if(this.row >0){
            this.row --;
            this.edit();
        }
    }
    void next(){
        if(this.row<tblXemay.getRowCount()-1){
            this.row++;
            this.edit();
        }
    }
    void last(){
        this.row = tblXemay.getRowCount()-1;
        this.edit();
    }
    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean fist = (this.row == 0);
        boolean last = (this.row == tblXemay.getRowCount() - 1);
        //trạng thái form
        txtMaxe.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        //trạng thái điều hướng
        btnFirst.setEnabled(edit && !fist);
        btnPrev.setEnabled(edit && !fist);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);

    }
    
    void fillComboBoxHangXe(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboHangXe.getModel();
        model.removeAllElements();
        List<HangXe> list = hxDAO.selectAll();
        for(HangXe hx : list){
            model.addElement(hx);
        }
//        this.fillTableByHangXe();
    }

    void fillTableByHangXe(){
        DefaultTableModel model = (DefaultTableModel) tblXemay.getModel();
        model.setRowCount(0);
        HangXe hx = (HangXe) cboHangXe.getSelectedItem();
        if(hx != null){
            List<Xe> list = xeDAO.selectByHangxe(hx.getMaHang());
            for(int i=0; i<list.size();i++){
                Xe xe = list.get(i);
                model.addRow(new Object[]{
                    xe.getMaXe(),
                    xe.getTenXe(),
                    xe.getMaMau(),
                    xe.getMaHang(),
                    xe.getSoLuong(),
                    xe.getGiaNhap(),
                    xe.getGiaBan(),
                    xe.getHinh()
                });
            }
        }
    }
    public boolean check(){
        
        if(txtTenxe.getText().isEmpty() ||
                txtSoluong.getText().isEmpty()||
                txtGianhap.getText().isEmpty()||txtGiaban.getText().isEmpty()){
                DialogHelper.alert(this, "Bạn chưa nhâp đủ dữ liệu");
                return false;
            
        }else {
            try{
                int soluong = Integer.parseInt(txtSoluong.getText());
                double gianhap = Double.parseDouble(txtGianhap.getText());
                double giaban = Double.parseDouble(txtGiaban.getText());
                if(soluong<=0 || gianhap <=0 || giaban <= 0){
                    DialogHelper.alert(this, "Dữ liệu sai");
                    return false;
                }
            }catch(Exception ex){
                DialogHelper.alert(this, "Dữ liệu không đúng");
                return false;
                
            }
        }
        
        return true;
        
    }
}
